[package]
name = "kg_moment"
version = "0.1.0"
authors = ["jacky.li <jacky.li@accenture.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = { version = "0.1.42" }
