[package]
name = "gui"
version = "0.1.0"
authors = ["jacky.li <jacky.li@accenture.com>"]
edition = "2018"



[dependencies]
cursive = "0.11"
orbtk = { git = "https://gitlab.redox-os.org/redox-os/orbtk.git" }




